project:
  type: book

book:
  title: "Ecosystemic Value Co-creation"
  author: "Armein Z. R Langi"
  date: "15/07/2026"
  chapters:
    - index.qmd
    - intro.qmd
    - ../moee_research_project/body.qmd 
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand
  pdf:
    documentclass: scrreprt



